package model.pixel;

/**
 * This interface represents the super pixel which is a collection of pixels in the image as 
 * generated by the cross stitched image pattern generator. The nearby pixels are combined 
 * using the nearest DMC color.
 */
public interface SuperPixel extends Pixel {

  /**
   * This methods return the SuperPixel height.
   *
   * @return height of the SuperPixel.
   */
  public int getSuperPixelHeight();

  /**
   * This methods return the SuperPixel width.
   *
   * @return width of the SuperPixel.
   */
  public int getSuperPixelWidth();

  /**
   * This methods return the SuperPixel unicode symbol.
   *
   * @return symbol for the SuperPixel.
   */
  String getSymbol();

  /**
   * Getter to get the dmc color during cross stitched pattern.
   * 
   * @return dmc color name for the pixel.
   */
  String getDmcColorName();

  /**
   * This methods return the SuperPixel postion y.
   *
   * @return SuperPixel postion y.
   */
  public int getSuperPixelPosY();

  /**
   * This methods return the SuperPixel postion x.
   *
   * @return SuperPixel postion x.
   */
  public int getSuperPixelPosX();
}
